#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'vbsp'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'boundbox.cpp',
		'brushbsp.cpp',
		'../../public/CollisionUtils.cpp',
		'csg.cpp',
		'cubemap.cpp',
		'detail.cpp',
		'detailObjects.cpp',
		'../../public/disp_common.cpp',
		'../../public/disp_powerinfo.cpp',
		'disp_vbsp.cpp',
		'faces.cpp',
		'glfile.cpp',
		'leakfile.cpp',
		'../../public/loadcmdline.cpp',
		'../../public/lumpfiles.cpp',
		'map.cpp',
		'manifest.cpp',
		'materialpatch.cpp',
		'materialsub.cpp',
		'../common/mstristrip.cpp',
		'nodraw.cpp',
		'normals.cpp',
		'overlay.cpp',
		'../common/physdll.cpp',
		'portals.cpp',
		'prtfile.cpp',
		'../../public/ScratchPad3D.cpp',
		'../common/scratchpad_helpers.cpp',
		'StaticProp.cpp',
		'textures.cpp',
		'tree.cpp',
		'../common/utilmatlib.cpp',
		'vbsp.cpp',
		'worldvertextransitionfixup.cpp',
		'writebsp.cpp',
		'../../public/zip_utils.cpp',
		'ivp.cpp',
		
        # Common files
        '../common/bsplib.cpp',
        '../../public/builddisp.cpp',
        '../../public/ChunkFile.cpp',
        '../common/cmdlib.cpp',
        '../../public/filesystem_helpers.cpp',
        '../../public/filesystem_init.cpp',
        '../common/filesystem_tools.cpp',
        '../common/map_shared.cpp',
        '../common/pacifier.cpp',
        '../common/polylib.cpp',
        '../common/scriplib.cpp',
        '../common/threads.cpp',
        '../common/tools_minidump.cpp',
	]
	includes = [
		'.',
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../common',
		'../vmpi'
	]
	defines = []
	libs = ['mathlib', 'tier0', 'tier1', 'tier2', 'tier3', 'vstdlib', 'bitmap', 'fgdlib', 'vtf', 'lzma']

	install_path = bld.env.LIBDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = 'CONSOLE,5.01',
		idx      = bld.get_taskgen_count()
	)
