#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'hammer'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	if bld.env.DEST_OS != 'win32':
		return
	
	source = [
		'main.cpp',
		'../public/tier0/memoverride.cpp',
		'hammer_launcher.rc'
	]
	includes = [
		'../public',
		'../public/tier0',
		'../public/tier1'
	]
	defines = []
	libs = ['tier0', 'tier1', 'vstdlib','appframework', 'USER32']

	install_path = bld.env.LIBDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
