#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'Hammer_launcher'

def options(opt):
	# stub
	return

def configure(conf):
	conf.define('CFLAGS', conf.env.CFLAGS)
	conf.define('LDFLAGS', conf.env.LINKFLAGS)

def build(bld):
	source = [
		'main.cpp'
	]

	includes = [
		'../public/',
		'../public/tier0',
		'../public/tier1',
	]	

	defines = []

	libs = ['appframework', 'tier0', 'tier1', 'vstdlib']

	install_path = bld.env.LIBDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx      = bld.get_taskgen_count()
	)
