#! /usr/bin/env python
# encoding: utf-8

from waflib import Utils
import os

top = '.'
PROJECT_NAME = 'bspzip'

def options(opt):
	# stub
	return

def configure(conf):
	return

def build(bld):
	source = [
		'../common/bsplib.cpp',
		'bspzip.cpp',
		'../common/cmdlib.cpp',
		'../../public/filesystem_helpers.cpp',
		'../../public/filesystem_init.cpp',
		'../common/filesystem_tools.cpp',
		'../../public/lumpfiles.cpp',
		'../common/scriplib.cpp',
		'../../public/zip_utils.cpp'
	]
	includes = [
		'../../public',
		'../../public/tier0',
		'../../public/tier1',
		'../common'
	]
	defines = []
	libs = ['mathlib', 'tier0', 'tier1', 'tier2', 'vstdlib', 'lzma']

	install_path = bld.env.LIBDIR
	bld(
		source   = source,
		target   = PROJECT_NAME,
		name     = PROJECT_NAME,
		features = 'c cxx cxxprogram',
		includes = includes,
		defines  = defines,
		use      = libs,
		install_path = install_path,
		subsystem = 'CONSOLE,5.01',
		idx      = bld.get_taskgen_count()
	)
